packages:
  - "apps/*"
  - "packages/*"

catalog:
  # NestJS
  "@nestjs/common": ^11.0.1
  "@nestjs/core": ^11.0.1
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/cli": ^11.0.0
  "@nestjs/schematics": ^11.0.0
  "@nestjs/testing": ^11.0.1
  # Temporal
  "@temporalio/activity": ^1.14.1
  "@temporalio/client": ^1.14.1
  "@temporalio/worker": ^1.14.1
  "@temporalio/workflow": ^1.14.1
  # Database
  drizzle-orm: ^0.45.0
  drizzle-zod: ^0.8.3
  drizzle-kit: ^0.31.0
  pg: ^8.11.3
  "@types/pg": ^8.11.0
  zod: ^3.25.0
  # Common
  typescript: ^5.9.2
  prettier: ^3.7.4
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.1
  "@eslint/js": ^9.39.1
  rxjs: ^7.8.1
  reflect-metadata: ^0.2.2
  # Testing
  jest: ^30.0.0
  "@types/jest": ^30.0.0
  ts-jest: ^29.2.5
  supertest: ^7.0.0
  "@types/supertest": ^6.0.2
  # Build tools
  ts-node: ^10.9.2
  ts-loader: ^9.5.2
  tsconfig-paths: ^4.2.0
  source-map-support: ^0.5.21
  # Other shared
  "@types/node": ^22.10.7
  "@types/express": ^5.0.0
  globals: ^16.5.0
  mingo: ^7.2.0
  uuid: ^11.1.0
  "@types/uuid": ^10.0.0
  typescript-eslint: ^8.50.0
  eslint-plugin-prettier: ^5.2.2
  "@eslint/eslintrc": ^3.2.0
