import {
  proxyActivities,
  defineSignal,
  defineQuery,
  setHandler,
  condition,
} from '@temporalio/workflow';

// ── Types ────────────────────────────────────────────────────────────────────

interface FlowNode {
  id: string;
  unit: string;
  label: string;
  config?: Record<string, unknown>;
  next: string[] | Record<string, string[]>;
  isTerminal?: boolean;
  isError?: boolean;
  isLoop?: boolean;
}

interface FlowContext {
  roleAssignments: Record<string, string>;
  variables: Record<string, unknown>;
  completedNodes: string[];
  nodeOutputs: Record<string, unknown>;
  activeNodes: string[];
}

type FlowInstanceStatus =
  | 'running'
  | 'waiting'
  | 'completed'
  | 'failed'
  | 'cancelled';

interface FlowInput {
  flowInstanceId: string;
  flowDefinitionId: string;
  graph: FlowNode[];
  context: FlowContext;
}

interface FlowStatus {
  flowInstanceId: string;
  status: string;
  activeNodes: string[];
  completedNodes: string[];
  history: Array<{
    nodeId: string;
    label: string;
    unitType: string;
    status: string;
    timestamp: string;
  }>;
}

type HumanDecision = Record<string, unknown> & {
  nodeId: string;
  action: string;
  comment?: string;
  data?: Record<string, unknown>;
};

// ── Signals ──────────────────────────────────────────────────────────────────

export const humanDecisionSignal =
  defineSignal<[HumanDecision]>('humanDecision');

// ── Queries ──────────────────────────────────────────────────────────────────

export const getFlowStatusQuery = defineQuery<FlowStatus>('getFlowStatus');

// ── Activities ───────────────────────────────────────────────────────────────

// Import activity types for type-safe proxying
import type * as unitActivities from '../activities/unit.activities';

const act = proxyActivities<typeof unitActivities>({
  startToCloseTimeout: '10 minutes',
  retry: { maximumAttempts: 3 },
});

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN WORKFLOW — The Generic Graph Executor
// ═══════════════════════════════════════════════════════════════════════════════

export async function executeFlowGraph(input: FlowInput) {
  const { flowInstanceId, graph } = input;
  const ctx: FlowContext = {
    roleAssignments: { ...input.context.roleAssignments },
    variables: { ...input.context.variables },
    completedNodes: [...(input.context.completedNodes || [])],
    nodeOutputs: { ...(input.context.nodeOutputs || {}) },
    activeNodes: [...(input.context.activeNodes || [])],
  };

  const history: FlowStatus['history'] = [];
  let overallStatus: FlowInstanceStatus = 'running';

  // Lookup helper
  const getNode = (id: string): FlowNode | undefined =>
    graph.find((n) => n.id === id);

  // Signal storage — human decisions arrive here
  const pendingDecisions: Map<string, HumanDecision> = new Map();

  setHandler(humanDecisionSignal, (decision: HumanDecision) => {
    pendingDecisions.set(decision.nodeId, decision);
  });

  // Query handler — UI can ask for current state anytime
  setHandler(
    getFlowStatusQuery,
    (): FlowStatus => ({
      flowInstanceId,
      status: overallStatus,
      activeNodes: [...ctx.activeNodes],
      completedNodes: [...ctx.completedNodes],
      history: [...history],
    }),
  );

  // ── Core: Execute a single node ──────────────────────────────────────────

  async function executeNode(nodeId: string): Promise<void> {
    const node = getNode(nodeId);
    if (!node) throw new Error(`Node ${nodeId} not found in graph`);

    // Load unit definition
    const unitDef = await act.loadUnitDefinition({ unitId: node.unit });

    // Merge configs: unit default config + node-level overrides
    const mergedConfig: Record<string, unknown> = {
      ...((unitDef.config as Record<string, unknown>) || {}),
      ...(node.config || {}),
    };

    // Create unit instance record
    const unitInstanceId = await act.createUnitInstance({
      flowInstanceId,
      unitDefinitionId: node.unit,
      nodeId: node.id,
      config: mergedConfig,
    });

    // Track as active
    ctx.activeNodes = [...ctx.activeNodes.filter((n) => n !== nodeId), nodeId];
    await act.updateFlowInstance({
      flowInstanceId,
      currentNodeIds: ctx.activeNodes,
    });

    history.push({
      nodeId,
      label: node.label,
      unitType: unitDef.type,
      status: 'started',
      timestamp: new Date().toISOString(),
    });

    let result: Record<string, unknown> | undefined;

    // ── TYPE-SPECIFIC EXECUTION ──────────────────────────────────────────

    switch (unitDef.type) {
      case 'DOCUMENT': {
        const docResult = await act.executeDocumentUnit({
          unitInstanceId,
          flowInstanceId,
          config: mergedConfig,
          context: ctx,
        });

        if (docResult.autoGenerated) {
          // Auto-generated documents complete immediately
          result = docResult;
        } else {
          // Manual documents: wait for user to fill in and signal completion
          const docCreatorRole =
            typeof mergedConfig.creator === 'string'
              ? mergedConfig.creator
              : 'initiator';
          const docCreatorId = docCreatorRole
            ? ctx.roleAssignments[docCreatorRole] ||
              ctx.roleAssignments['initiator'] ||
              ''
            : '';

          if (docCreatorId) {
            await act.createNotification({
              recipientId: docCreatorId,
              type: 'task_assigned',
              title: `Document Required: ${node.label}`,
              message: `Please fill in the document "${node.label}" for flow "${input.flowDefinitionId}".`,
              flowInstanceId,
              flowDefinitionId: input.flowDefinitionId,
              unitInstanceId,
            });
          }

          overallStatus = 'waiting';

          const docTimeoutMs = parseTimeout(
            typeof mergedConfig.timeout === 'string'
              ? mergedConfig.timeout
              : '168h',
          );

          const docSignalReceived = await condition(
            () => pendingDecisions.has(nodeId),
            docTimeoutMs,
          );

          overallStatus = 'running';

          if (!docSignalReceived) {
            result = { action: 'TIMEOUT', documentId: docResult.documentId };
            await act.handleTimeout({
              unitInstanceId,
              flowInstanceId,
              nodeId,
            });
          } else {
            const decision = pendingDecisions.get(nodeId);
            pendingDecisions.delete(nodeId);

            await act.completeDocumentUnit({
              unitInstanceId,
              documentId: docResult.documentId,
              action:
                typeof decision?.action === 'string'
                  ? decision.action
                  : 'COMPLETE',
              comment:
                typeof decision?.comment === 'string'
                  ? decision.comment
                  : undefined,
            });

            result = {
              ...decision,
              documentId: docResult.documentId,
            };
          }
        }
        break;
      }

      case 'ACTION': {
        // Determine assignee from config + role assignments
        const assigneeRole =
          typeof mergedConfig.assignee === 'string'
            ? mergedConfig.assignee
            : '';
        const assigneeId = assigneeRole
          ? ctx.roleAssignments[assigneeRole] || ''
          : '';

        await act.activateActionUnit({
          unitInstanceId,
          assigneeId,
          flowInstanceId,
          allowedActions: Array.isArray(mergedConfig.allowedActions)
            ? (mergedConfig.allowedActions as string[])
            : [],
        });

        // Notify the assignee about the new action
        if (assigneeId) {
          await act.createNotification({
            recipientId: assigneeId,
            type: 'task_assigned',
            title: `Action Required: ${node.label}`,
            message: `You have been assigned an action in flow "${input.flowDefinitionId}".`,
            flowInstanceId,
            flowDefinitionId: input.flowDefinitionId,
            unitInstanceId,
          });
        }

        // Update flow status to waiting
        overallStatus = 'waiting';

        // PAUSE — wait for human signal
        const timeoutMs = parseTimeout(
          typeof mergedConfig.timeout === 'string'
            ? mergedConfig.timeout
            : '168h',
        );

        const signalReceived = await condition(
          () => pendingDecisions.has(nodeId),
          timeoutMs,
        );

        overallStatus = 'running';

        if (!signalReceived) {
          result = { action: 'TIMEOUT' };
          await act.handleTimeout({
            unitInstanceId,
            flowInstanceId,
            nodeId,
          });
        } else {
          result = pendingDecisions.get(nodeId);
          pendingDecisions.delete(nodeId);
        }

        if (!result) {
          result = { action: 'ERROR', comment: 'No decision data received' };
        }

        const actionAction =
          typeof result?.action === 'string' ? result.action : 'ERROR';
        const actionComment =
          typeof result?.comment === 'string' ? result.comment : undefined;

        await act.completeActionUnit({
          unitInstanceId,
          action: actionAction,
          comment: actionComment,
        });

        // Notify flow creator about the action result
        const actionCreatorId = ctx.roleAssignments['initiator'] || '';
        if (actionCreatorId && actionCreatorId !== assigneeId) {
          const isRejection =
            actionAction === 'REJECT' || actionAction === 'REQUEST_CHANGE';
          await act.createNotification({
            recipientId: actionCreatorId,
            type: isRejection ? 'rejection' : 'action_completed',
            title: isRejection
              ? `${actionAction === 'REJECT' ? 'Rejected' : 'Change Requested'}: ${node.label}`
              : `Completed: ${node.label}`,
            message: `${node.label} — ${actionAction.toLowerCase()}${actionComment ? ': ' + actionComment : ''}.`,
            flowInstanceId,
            flowDefinitionId: input.flowDefinitionId,
            unitInstanceId,
            actorId: assigneeId,
          });
        }
        break;
      }

      case 'TASK': {
        const taskAssigneeRole =
          typeof mergedConfig.assignee === 'string'
            ? mergedConfig.assignee
            : '';
        const taskAssigneeId = taskAssigneeRole
          ? ctx.roleAssignments[taskAssigneeRole] || ''
          : '';

        await act.activateTaskUnit({
          unitInstanceId,
          assigneeId: taskAssigneeId,
          flowInstanceId,
          instructions: node.label,
        });

        // Notify the assignee about the new task
        if (taskAssigneeId) {
          await act.createNotification({
            recipientId: taskAssigneeId,
            type: 'task_assigned',
            title: `Task Assigned: ${node.label}`,
            message: `You have been assigned a task in flow "${input.flowDefinitionId}".`,
            flowInstanceId,
            flowDefinitionId: input.flowDefinitionId,
            unitInstanceId,
          });
        }

        overallStatus = 'waiting';

        const timeoutMs = parseTimeout(
          typeof mergedConfig.deadline === 'string'
            ? mergedConfig.deadline
            : '72h',
        );

        const signalReceived = await condition(
          () => pendingDecisions.has(nodeId),
          timeoutMs,
        );

        overallStatus = 'running';

        if (!signalReceived) {
          result = { action: 'TIMEOUT' };
          await act.handleTimeout({
            unitInstanceId,
            flowInstanceId,
            nodeId,
          });
        } else {
          result = pendingDecisions.get(nodeId);
          pendingDecisions.delete(nodeId);
        }

        if (!result) {
          result = { action: 'ERROR', comment: 'No decision data received' };
        }

        await act.completeTaskUnit({
          unitInstanceId,
          result: result || {},
        });
        break;
      }

      case 'CONDITION': {
        result = await act.evaluateCondition({
          unitInstanceId,
          flowInstanceId,
          expression:
            typeof mergedConfig.expression === 'string'
              ? mergedConfig.expression
              : '',
          context: ctx,
        });
        // result = { branch: "true" } or { branch: "SIGN" } etc.
        break;
      }

      case 'NOTIFICATION': {
        const recipientRole =
          typeof mergedConfig.recipients === 'string'
            ? mergedConfig.recipients
            : '';
        const recipientId = recipientRole
          ? ctx.roleAssignments[recipientRole] || ''
          : '';

        await act.sendNotification({
          unitInstanceId,
          recipientId,
          flowInstanceId,
          channel: Array.isArray(mergedConfig.channel)
            ? (mergedConfig.channel as string[])
            : ['portal'],
          message:
            typeof mergedConfig.message === 'string'
              ? mergedConfig.message
              : node.label,
        });
        result = { status: 'notified' };
        break;
      }

      case 'AUTOMATION': {
        result = await act.executeAutomation({
          unitInstanceId,
          flowInstanceId,
          handler:
            typeof mergedConfig.handler === 'string'
              ? mergedConfig.handler
              : '',
          config: mergedConfig,
          context: ctx,
        });
        break;
      }

      case 'PARALLEL': {
        // Parallel just marks the fork point.
        // The next resolution handles the actual forking.
        await act.updateUnitInstance({
          unitInstanceId,
          status: 'completed',
          output: { forked: true },
        });
        result = { forked: true };
        break;
      }

      case 'GATE': {
        // Gate just marks convergence. The parallel handler waits for all
        // branches before advancing past the gate.
        await act.updateUnitInstance({
          unitInstanceId,
          status: 'completed',
          output: { gateReached: true },
        });
        result = { gateReached: true };
        break;
      }
    }

    // ── Record completion ────────────────────────────────────────────────

    ctx.completedNodes.push(nodeId);
    ctx.nodeOutputs[nodeId] = result;
    ctx.activeNodes = ctx.activeNodes.filter((n) => n !== nodeId);

    history.push({
      nodeId,
      label: node.label,
      unitType: unitDef.type,
      status: 'completed',
      timestamp: new Date().toISOString(),
    });

    const resultAction =
      typeof result?.action === 'string' ? result.action : undefined;
    const resultBranch =
      typeof result?.branch === 'string' ? result.branch : undefined;

    await act.recordAuditEntry({
      flowInstanceId,
      unitInstanceId,
      actorId: null,
      action: resultAction || 'COMPLETE',
      details: result,
    });

    // ── Resolve next nodes ───────────────────────────────────────────────

    let nextNodeIds: string[] = [];

    if (Array.isArray(node.next)) {
      nextNodeIds = node.next;
    } else if (typeof node.next === 'object' && node.next !== null) {
      // Branch resolution — match by branch key or action
      const branchKey = resultBranch || resultAction || 'default';
      nextNodeIds = node.next[branchKey] || node.next['default'] || [];
    }

    if (nextNodeIds.length === 0) {
      // Terminal node — this branch is done
      return;
    }

    // ── Handle PARALLEL forking ──────────────────────────────────────────

    if (unitDef.type === 'PARALLEL' && nextNodeIds.length > 1) {
      // Find the GATE node that these branches converge on
      const gateNodeId = findConvergenceGate(graph, nextNodeIds);

      // Execute all branches in parallel
      const branchPromises = nextNodeIds.map((nid) => executeNode(nid));
      await Promise.all(branchPromises);

      // After all branches complete, continue from gate
      if (gateNodeId) {
        await executeNode(gateNodeId);
      }
      return;
    }

    // ── Sequential next ──────────────────────────────────────────────────

    for (const nextId of nextNodeIds) {
      const nextNode = getNode(nextId);

      // Handle loop-back
      if (nextNode?.isLoop || ctx.completedNodes.includes(nextId)) {
        // Reset the loop target and all downstream nodes
        ctx.completedNodes = ctx.completedNodes.filter(
          (n) => !isDownstream(graph, nextId, n) && n !== nextId,
        );
        // Clear outputs for reset nodes
        for (const resetNode of [...ctx.completedNodes]) {
          if (isDownstream(graph, nextId, resetNode)) {
            delete ctx.nodeOutputs[resetNode];
          }
        }
      }

      await executeNode(nextId);
    }
  }

  // ── Start execution from root node ─────────────────────────────────────

  try {
    const rootNode = graph.find((n) => n.id === '1');
    if (!rootNode) throw new Error('Flow graph must have a node with id "1"');

    await executeNode('1');
    overallStatus = 'completed';
  } catch (error) {
    overallStatus = 'failed';
    throw error;
  } finally {
    await act.updateFlowInstance({
      flowInstanceId,
      status: overallStatus,
    });

    // Notify the flow creator about completion/failure
    const creatorId = ctx.roleAssignments['initiator'] || '';
    if (
      creatorId &&
      (overallStatus === 'completed' || overallStatus === 'failed')
    ) {
      await act
        .createNotification({
          recipientId: creatorId,
          type:
            overallStatus === 'completed' ? 'flow_completed' : 'flow_failed',
          title:
            overallStatus === 'completed'
              ? `Flow Completed: ${input.flowDefinitionId}`
              : `Flow Failed: ${input.flowDefinitionId}`,
          message: `Your flow "${input.flowDefinitionId}" has ${overallStatus}.`,
          flowInstanceId,
          flowDefinitionId: input.flowDefinitionId,
        })
        .catch(() => {
          /* best-effort */
        });
    }
  }

  return {
    status: overallStatus,
    completedNodes: ctx.completedNodes,
    outputs: ctx.nodeOutputs,
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Find the GATE node that parallel branches converge on.
 * Walks each branch forward to find the first common target.
 */
function findConvergenceGate(
  graph: FlowNode[],
  branchStartIds: string[],
): string | null {
  const branchTargets = branchStartIds.map((id) => {
    const node = graph.find((n) => n.id === id);
    if (!node) return [];
    return Array.isArray(node.next)
      ? node.next
      : Object.values(node.next).flat();
  });

  if (branchTargets.length === 0) return null;

  // Find intersection of all branch targets
  const common = branchTargets.reduce((acc, targets) =>
    acc.filter((t) => targets.includes(t)),
  );

  return common[0] || null;
}

/**
 * Check if targetId is reachable from startId by walking the graph.
 */
function isDownstream(
  graph: FlowNode[],
  startId: string,
  targetId: string,
): boolean {
  const visited = new Set<string>();
  const queue = [startId];

  while (queue.length > 0) {
    const current = queue.shift()!;
    if (current === targetId) return true;
    if (visited.has(current)) continue;
    visited.add(current);

    const node = graph.find((n) => n.id === current);
    if (!node) continue;

    const nexts = Array.isArray(node.next)
      ? node.next
      : Object.values(node.next).flat();
    queue.push(...nexts);
  }

  return false;
}

/**
 * Parse a timeout string like "72h", "168h", "30m" into milliseconds.
 */
function parseTimeout(timeout: string): number {
  const match = timeout.match(/^(\d+)\s*(ms|s|m|h|d)$/);
  if (!match) return 7 * 24 * 60 * 60 * 1000; // default 7 days

  const value = parseInt(match[1], 10);
  switch (match[2]) {
    case 'ms':
      return value;
    case 's':
      return value * 1000;
    case 'm':
      return value * 60 * 1000;
    case 'h':
      return value * 60 * 60 * 1000;
    case 'd':
      return value * 24 * 60 * 60 * 1000;
    default:
      return 7 * 24 * 60 * 60 * 1000;
  }
}
